# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
UsuariosBundle:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.xml"
    prefix:   /

UvmediaCoreBundle:
    resource: "@UvmediaCoreBundle/Resources/config/routing.xml"
    prefix:   /
    
EncuestaCoreBundle:
    resource: "@EncuestaBundle/Resources/config/routing.yml"
    prefix:   /
