UvmediaCoreBundle:
    resource: "@UvmediaCoreBundle/Resources/config/routing.xml"
    prefix:   /

EncuestaBundle:
    resource: "@EncuestaBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
