UsuariosBundle_homepage:
    pattern:  /useradmin/
    defaults: { _controller: UsuariosBundle:UserAdmin:index }
    
UsuariosBundle_newuser:
    pattern: /useradmin/user/new
    defaults: { _controller: UsuariosBundle:UserAdmin:newUsuario }

UsuariosBundle_edituser:
    pattern: /useradmin/user/edit/{id_usuario}
    defaults: { _controller: UsuariosBundle:UserAdmin:editUsuario }
    
UsuariosBundle_deleteuser:
    pattern: /useradmin/user/delete/{id_usuario}
    defaults: { _controller: UsuariosBundle:UserAdmin:deleteUsuario }
    
UsuariosBundle_newgroup:
    pattern: /useradmin/group/new
    defaults: { _controller: UsuariosBundle:UserAdmin:newGrupo }

UsuariosBundle_editgroup:
    pattern: /useradmin/group/edit/{id_grupo}
    defaults: { _controller: UsuariosBundle:UserAdmin:editGrupo }
    
# TODO el resto de las operaciones para grupos    
    
UsuariosBundle_newapp:
    pattern: /useradmin/app/new
    defaults: { _controller: UsuariosBundle:UserAdmin:newAplicacion }

# TODO el resto de las operaciones para aplicaciones

#UsuariosBundle_aplicacion:
#    resource: @UsuariosBundle/Resources/config/routing/aplicacion.yml
#    prefix: /crudaplicacion/

UsuariosBundle_login:
    pattern: /login
    defaults: { _controller: UsuariosBundle:UserLogin:login }
    
UsuariosBundle_login_check:
    pattern: /login_check
