UsuariosBundle_homepage:
    pattern:  /useradmin
    defaults: { _controller: UsuariosBundle:UserAdmin:index }
    
UsuariosBundle_newuser:
    pattern: /useradmin/user/new
    defaults: { _controller: UsuariosBundle:UserAdmin:newUsuario }
    
UsuariosBundle_newgroup:
    pattern: /useradmin/group/new
    defaults: { _controller: UsuariosBundle:UserAdmin:newGrupo }
