EncuestaBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EncuestaBundle:Default:index }

EncuestaBundle_preguntaadmin:
    pattern: /preguntaadmin/
    defaults: { _controller: "EncuestaBundle:Pregunta:index" }