EncuestaBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EncuestaBundle:Default:index }

EncuestaBundle_preguntaadmin:
    resource: "@EncuestaBundle/Resources/config/routing/pregunta.yml"
    prefix: /preguntaadmin/