parameters:
#    encuesta.example.class: Uvmedia\EncuestaBundle\Example

services:
#    encuesta.example:
#        class: %encuesta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
